# Generated by Django 5.2.4 on 2025-07-25 23:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprecla', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_reclamation', models.CharField(choices=[('qualite', 'Problème de qualité'), ('livraison', 'Erreur de livraison'), ('manquant', 'Produit manquant'), ('quantite', 'Mauvaise quantité livrée'), ('commande', 'Erreur de commande'), ('retard', 'Retard de livraison')], max_length=20, verbose_name='Type de réclamation')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre de la réclamation')),
                ('description', models.TextField(verbose_name='Description détaillée')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours de traitement'), ('resolu', 'Résolu'), ('rejete', 'Rejeté')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Réclamation',
                'verbose_name_plural': 'Réclamations',
                'ordering': ['-date_creation'],
            },
        ),
    ]
