# Generated by Django 5.2.4 on 2025-07-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprecla', '0004_remove_userprofile_role_rolechangerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('commercial', 'Commercial'), ('qualite', 'Agent Qualité'), ('admin', 'Administrateur')], default='client', max_length=20, verbose_name='Rôle'),
        ),
    ]
