# Generated by Django 5.2.4 on 2025-07-28 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprecla', '0005_userprofile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('est_membre', models.CharField(choices=[('yes', 'Oui, je suis membre'), ('no', 'Non, je ne suis pas membre')], max_length=10, verbose_name='Êtes-vous membre de cette société ?')),
                ('preuve_justification', models.TextField(help_text='Veuillez fournir une preuve ou justification de votre statut', verbose_name='Preuve ou justification')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('rejected', 'Rejetée')], default='pending', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Demande simple',
                'verbose_name_plural': 'Demandes simples',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
    ]
