# Generated by Django 5.2.4 on 2025-07-28 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprecla', '0006_simplerequest_remove_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplerequest',
            name='admin_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Commentaire administrateur'),
        ),
        migrations.AddField(
            model_name='simplerequest',
            name='type_demande',
            field=models.CharField(choices=[('commercial', 'Commercial'), ('qualite', 'Agent Qualité')], default=1, max_length=20, verbose_name='Type de demande'),
            preserve_default=False,
        ),
    ]
