# Generated by Django 5.2.4 on 2025-07-29 00:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprecla', '0007_simplerequest_admin_comment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simplerequest',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='simplerequest',
            name='prenom',
        ),
        migrations.AddField(
            model_name='simplerequest',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='RoleChangeRequest',
        ),
    ]
