# Generated by Django 5.2.4 on 2025-07-29 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprecla', '0008_remove_simplerequest_nom_remove_simplerequest_prenom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='est_membre',
            field=models.CharField(blank=True, choices=[('yes', 'Oui, je suis membre'), ('no', 'Non, je ne suis pas membre')], max_length=10, null=True, verbose_name='Êtes-vous membre de cette société ?'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preuve_justification',
            field=models.TextField(blank=True, help_text='Veuillez fournir une preuve ou justification de votre statut', null=True, verbose_name='Preuve ou justification'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='type_demande',
            field=models.CharField(blank=True, choices=[('commercial', 'Commercial'), ('qualite', 'Agent Qualité')], max_length=20, null=True, verbose_name='Type de demande'),
        ),
    ]
