# Generated by Django 5.2.4 on 2025-07-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprecla', '0009_userprofile_est_membre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='type_demande',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='admin_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Commentaire administrateur'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='pending', max_length=20, verbose_name="Statut d'approbation"),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('client', 'Client'), ('commercial', 'Commercial'), ('qualite', 'Agent Qualité')], max_length=20, null=True, verbose_name="Type d'utilisateur"),
        ),
    ]
