# Generated by Django 5.2.4 on 2025-08-03 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprecla', '0010_remove_userprofile_type_demande_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReclamationFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='reclamation_files/%Y/%m/%d/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('reclamation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='apprecla.reclamation')),
            ],
            options={
                'verbose_name': 'Fichier de réclamation',
                'verbose_name_plural': 'Fichiers de réclamation',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
