# Generated by Django 5.2.4 on 2025-08-03 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprecla', '0011_reclamationfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reclamationfile',
            name='file',
        ),
        migrations.AddField(
            model_name='reclamationfile',
            name='client_name',
            field=models.CharField(default=1, max_length=255, verbose_name='Nom du client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reclamationfile',
            name='clientid',
            field=models.IntegerField(default=1, verbose_name='ID du client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reclamationfile',
            name='jointpiece',
            field=models.FileField(default=1, upload_to='reclamation_files/%Y/%m/%d/', verbose_name='Pièce jointe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reclamationfile',
            name='reclamationid',
            field=models.IntegerField(default=2, verbose_name='ID de la réclamation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reclamationfile',
            name='file_name',
            field=models.CharField(max_length=255, verbose_name='Nom du fichier'),
        ),
        migrations.AlterField(
            model_name='reclamationfile',
            name='file_type',
            field=models.CharField(max_length=50, verbose_name='Type de fichier'),
        ),
        migrations.AlterField(
            model_name='reclamationfile',
            name='reclamation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='apprecla.reclamation', verbose_name='Réclamation'),
        ),
        migrations.AlterField(
            model_name='reclamationfile',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date d'upload"),
        ),
    ]
