# Generated by Django 5.2.4 on 2025-08-03 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprecla', '0012_remove_reclamationfile_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=100, verbose_name='ID du client')),
                ('client_name', models.CharField(max_length=200, verbose_name='Nom du client')),
                ('piece_jointe', models.FileField(upload_to='photos_reclamations/%Y/%m/%d/', verbose_name='Pièce jointe (photo/vidéo)')),
                ('nom_fichier', models.CharField(max_length=255, verbose_name='Nom du fichier')),
                ('type_fichier', models.CharField(choices=[('image', 'Image'), ('video', 'Vidéo')], max_length=20, verbose_name='Type de fichier')),
                ('taille_fichier', models.BigIntegerField(verbose_name='Taille du fichier (bytes)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description optionnelle')),
                ('date_upload', models.DateTimeField(auto_now_add=True, verbose_name="Date d'upload")),
                ('reclamation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='apprecla.reclamation')),
            ],
            options={
                'verbose_name': 'Photo/Vidéo de réclamation',
                'verbose_name_plural': 'Photos/Vidéos de réclamations',
                'ordering': ['-date_upload'],
            },
        ),
        migrations.DeleteModel(
            name='ReclamationFile',
        ),
    ]
