# Generated by Django 5.2.4 on 2025-08-03 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprecla', '0013_photo_delete_reclamationfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='taille_fichier',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Taille du fichier (bytes)'),
        ),
    ]
