# Generated by Django 5.2.4 on 2025-08-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprecla', '0014_alter_photo_taille_fichier'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamation',
            name='societe',
            field=models.CharField(blank=True, choices=[('vitagrain', 'Vitagrain'), ('kenz_maroc', 'Kenz Maroc'), ('kenzpat', 'KenzPat')], max_length=20, null=True, verbose_name='Société'),
        ),
    ]
