# Generated by Django 5.2.4 on 2025-08-13 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprecla', '0015_reclamation_societe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamation',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('en_traitement_qualite', 'En traitement par agent qualité'), ('resolu', 'Résolu'), ('rejete', 'Rejeté')], default='en_attente', max_length=25, verbose_name='Statut'),
        ),
    ]
