# Generated by Django 5.2.5 on 2025-08-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprecla', '0016_alter_reclamation_statut'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name="Nom de l'article")),
                ('societe', models.CharField(choices=[('vitagrain', 'Vitagrain'), ('kenz_maroc', 'Kenz Maroc'), ('kenzpat', 'KenzPat')], max_length=20, verbose_name='Société')),
                ('image', models.ImageField(upload_to='articles/', verbose_name="Image de l'article")),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
        migrations.AddField(
            model_name='reclamation',
            name='articles',
            field=models.ManyToManyField(blank=True, related_name='reclamations', to='apprecla.article', verbose_name='Articles concernés'),
        ),
    ]
