# Generated by Django 5.2.5 on 2025-08-14 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apprecla', '0017_article_reclamation_articles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reclamation',
            name='articles',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
