# Generated by Django 5.2.5 on 2025-08-14 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprecla', '0018_remove_reclamation_articles_delete_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name="Nom de l'article")),
                ('societe', models.CharField(blank=True, choices=[('vitagrain', 'Vitagrain'), ('kenz_maroc', 'Kenz Maroc'), ('kenzpat', 'KenzPat')], max_length=20, null=True, verbose_name='Société')),
            ],
        ),
        migrations.CreateModel(
            name='ReclamationArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apprecla.article')),
                ('reclamation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apprecla.reclamation')),
            ],
            options={
                'verbose_name': 'Article de réclamation',
                'verbose_name_plural': 'Articles de réclamation',
                'unique_together': {('reclamation', 'article')},
            },
        ),
        migrations.AddField(
            model_name='reclamation',
            name='articles',
            field=models.ManyToManyField(blank=True, related_name='reclamations', through='apprecla.ReclamationArticle', to='apprecla.article', verbose_name='Articles concernés'),
        ),
    ]
