# Generated by Django 5.2.5 on 2025-08-14 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprecla', '0019_article_reclamationarticle_reclamation_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.URLField(blank=True, help_text="URL de l'image du produit (ex: depuis e-xportmorocco.com)", max_length=500, null=True, verbose_name="URL de l'image"),
        ),
    ]
