# Generated by Django 5.2.5 on 2025-08-14 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprecla', '0020_article_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.CharField(choices=[('500g', '500g'), ('1kg', '1 KG'), ('2kg', '2 KG'), ('5kg', '5 KG'), ('10kg', '10 KG'), ('25kg', '25 KG'), ('50kg', '50 KG')], max_length=10, verbose_name='Poids')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix (MAD)')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='apprecla.article')),
            ],
            options={
                'verbose_name': "Variante d'article",
                'verbose_name_plural': "Variantes d'articles",
                'ordering': ['weight'],
                'unique_together': {('article', 'weight')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='reclamationarticle',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='reclamationarticle',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apprecla.articlevariant', verbose_name='Variante (poids)'),
        ),
        migrations.AlterUniqueTogether(
            name='reclamationarticle',
            unique_together={('reclamation', 'article', 'variant')},
        ),
    ]
