# Generated by Django 5.2.5 on 2025-08-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprecla', '0021_articlevariant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, help_text='Image du produit', null=True, upload_to='articles/%Y/%m/%d/', verbose_name="Image de l'article"),
        ),
    ]
