# Generated by Django 5.2.5 on 2025-08-23 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprecla', '0024_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.AddField(
            model_name='reclamationarticle',
            name='article_image_url',
            field=models.URLField(blank=True, help_text="URL de l'image de l'article sélectionné", null=True, verbose_name="URL de l'image de l'article"),
        ),
        migrations.AlterField(
            model_name='article',
            name='societe',
            field=models.CharField(blank=True, choices=[('vetadis', 'Vetadis'), ('kenz_maroc', 'Kenz Maroc'), ('kenzpat', 'KenzPat')], max_length=20, null=True, verbose_name='Société'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='societe',
            field=models.CharField(blank=True, choices=[('vetadis', 'Vetadis'), ('kenz_maroc', 'Kenz Maroc'), ('kenzpat', 'KenzPat')], max_length=20, null=True, verbose_name='Société'),
        ),
    ]
