# Generated by Django 5.2.5 on 2025-08-26 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprecla', '0025_delete_company_reclamationarticle_article_image_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reclamationarticle',
            name='article_image_url',
        ),
        migrations.CreateModel(
            name='ReclamationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reclamation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='apprecla.reclamation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamation_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message de réclamation',
                'verbose_name_plural': 'Messages de réclamation',
                'ordering': ['created_at'],
            },
        ),
    ]
