# Generated by Django 5.2.5 on 2025-08-27 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprecla', '0026_remove_reclamationarticle_article_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamationarticle',
            name='photo_article',
            field=models.ImageField(blank=True, help_text="Photo spécifique de l'article pour cette réclamation", null=True, upload_to='reclamation_articles/%Y/%m/%d/', verbose_name="Photo de l'article"),
        ),
    ]
