# Generated by Django 5.2.5 on 2025-08-27 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprecla', '0027_reclamationarticle_photo_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reclamationarticle',
            name='photo_article',
        ),
        migrations.AddField(
            model_name='reclamationarticle',
            name='image_article',
            field=models.ForeignKey(blank=True, help_text="Image de l'article pour cette réclamation", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reclamation_articles_images', to='apprecla.article', verbose_name="Image de l'article"),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='articles',
            field=models.ManyToManyField(blank=True, related_name='reclamations', through='apprecla.ReclamationArticle', through_fields=('reclamation', 'article'), to='apprecla.article', verbose_name='Articles concernés'),
        ),
    ]
