# Generated by Django 5.2.5 on 2025-08-27 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apprecla', '0028_remove_reclamationarticle_photo_article_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reclamationarticle',
            name='image_article',
        ),
    ]
