# Generated by Django 5.2.5 on 2025-09-02 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprecla', '0029_remove_reclamationarticle_image_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsable', models.CharField(max_length=200, verbose_name='Responsable')),
                ('date_rapport', models.DateField(verbose_name='Date du rapport')),
                ('objet', models.CharField(max_length=255, verbose_name='Objet du rapport')),
                ('description_probleme', models.TextField(verbose_name='Description du problème')),
                ('actions', models.TextField(verbose_name='Actions entreprises')),
                ('resultat', models.TextField(verbose_name='Résultat')),
                ('conclusion', models.TextField(verbose_name='Conclusion')),
                ('recommandation', models.TextField(blank=True, null=True, verbose_name='Recommandation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reclamation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='apprecla.reclamation')),
            ],
            options={
                'verbose_name': 'Rapport',
                'verbose_name_plural': 'Rapports',
                'ordering': ['-created_at'],
            },
        ),
    ]
